name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run typecheck

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v4

  build:
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run astro:build

      - name: Prune dev dependencies
        run: npm prune --production

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: still-they-shine
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: [build, codeql]
    permissions:
      id-token: write
      contents: read

    if: github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, '[skip deploy]')
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: still-they-shine

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C50EC97922514FB3BFA46F8BDAF921EE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A42443BFCF674F979051E82B31CD33C6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2503868858414E02BF2D60C0333A84C5 }}

      - name: "Deploy to Azure"
        id: deploy-to-azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "still-they-shine"
          slot-name: "Production"
          package: .
          startup-command: "node ./dist/server/entry.mjs"
